version: '3.8'

services:
  zola:
    working_dir: /app
    build: 
      context: ./docker
    command: serve --interface 0.0.0.0 --port 8080 --base-url localhost
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "1024:1024"